### ISSUE TITLE
Resources?

### ISSUE THREAD

**Issue by nathanpelt** [PiStuffing/Quadcopter#2]
Hi this is Nathan. I have a few questions regarding your raspberry pi quad-rotor. What development environment did you use to write your code? I looked over your pdf but it did not mention any development environment. Also if you would have any names or links to resources or books on writing embedded code like your python i2c code that would be great.  I know how to program in a few languages but really haven't done any embedded development before. Thanks for your time.

**Comment by PiStuffing** [comment]
Hi Nathan,

I didn't use a development environment - python is such an easy language to write that I just wrote the code in a text editor, and ran it to test it.  Because a Raspberry Pi is a true linux computer rather than an embedded system like an Arduino, there's no need for a separate computer to cross-complile / load the code.  Everything can be done on the RPi.

The basic I2C code at the top of Quadcopter.py came from an example from adafruit: https://learn.adafruit.com/adafruit-16-channel-servo-driver-with-raspberry-pi/overview.  I then added calls to it to add error protection and higher performance.  There is a python library (python-smbus in the Raspian distribution) that does most of the work, and my code just calls the various read and write calls provided by the smbus library.

Hope that helps,

Andy
