### ISSUE TITLE
Regarding orientation of sensors.

### ISSUE THREAD

**Issue by jovinjijo** [PiStuffing/Quadcopter#3]
Reading through the documentation and code, I couldn't find how the sensors (MPU6050 and Compass) should be fixed. 
Is there a default orientation? If yes, can it be changed? Is it hard coded in the python script?
Any help would be great.

**Comment by PiStuffing** [comment]
Take a look here: http://blog.pistuffing.co.uk/wp-content/uploads/2017/05/DSC01347.jpg

I use the Sparkfun MPU-9250 breakout.  It's in the middle of the PCB in the picture from the link.  The accelerometer X axis points "forwards" from the drone point of view (i.e. leftwards pointing in the picture), y axis points left from drone POV (downwards in the picture), and Z axis upwards (towards the camera in the picture).  This is what the python is coded to match.

The easiest way to change this orientation would be in readFIFO().  This is the deepest point where the code assigns X forwards, Y left, Z up and names the FIFO register contents that way.  So that's the point you could allow for the MPU9250 X register to actually be "right" for example.

**Comment by jovinjijo** [comment]
Okay. That was really helpful.
Thank you.
